### ISSUE TITLE
I get JET client error, after run npx ojet build web

### ISSUE THREAD

**Issue by simongaocd** [oracle-devrel/oci-generative-ai-jet-ui#3]
ci-generative-ai-jet-ui/app/node_modules/@oracle/oraclejet/dist/custom-tsc/compile.js:61
    if (parsedJsonConfig?.raw?.compilerOptions?.['_JET_translationBundleIds']) {
                         ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/opc/oci-generative-ai-jet-ui/app/node_modules/@oracle/oraclejet/dist/custom-tsc/index.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by peppertech** [comment]
Hello, can you please run these two commands from the root of the /app folder.

node --version
npx ojet --version

I'm guessing that you've got an old version of Nodejs being used.  We require at least Node 16 and recommend the latest LTS release.

**Comment by peppertech** [comment]
I'm going to close this issue as there hasn't been any reply in over a week.  Please feel free to re-open if there is still a reproduceable problem.
